#!/usr/bin/env python3
"""Browser interaction tests with deterministic, visibly labelled demo data."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json, re
ROOT=Path(__file__).resolve().parents[1]
SHOTS=ROOT/'tests/screenshots';SHOTS.mkdir(exist_ok=True)
results=[]
def load_ui(page, demo=True, menu=False):
    # Managed Chromium blocks even local URL navigation in this test environment.
    # Load identical UI assets into an isolated document; only the explicit
    # preview flag and fixture loader are adapted in this in-memory test copy.
    html=(ROOT/'ui/index.html').read_text()
    html=re.sub(r'<meta http-equiv="Content-Security-Policy"[^>]*>', '', html)
    html=html.replace('<link rel="stylesheet" href="styles.css">','').replace('<script src="app.js"></script>','')
    page.set_content(html)
    page.add_style_tag(content=(ROOT/'ui/styles.css').read_text())
    if menu: page.evaluate("window.PULSE_MODE='menu'")
    js=(ROOT/'ui/app.js').read_text()
    if demo:
        js=js.replace("const demo=!native&&new URLSearchParams(location.search).get('demo')==='1';", "const demo=!native&&true;")
        js=js.replace("if(demo){const script=document.createElement('script');script.src='demo.js';document.head.appendChild(script);}", '')
    page.add_script_tag(content=js)
    if demo: page.add_script_tag(content=(ROOT/'ui/demo.js').read_text())
def record(name,condition=True):
    assert condition,name
    results.append({'test':name,'result':'PASS'})
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--allow-file-access-from-files'])
    page=browser.new_page(viewport={'width':1120,'height':820},device_scale_factor=1)
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    load_ui(page);page.wait_for_function('window.Pulse.getState().snapshot !== null')
    record('Demo data is explicitly labelled',page.get_by_text('Demo data',exact=True).is_visible())
    record('Overview has six live metric cards',page.locator('.metric-card').count()==6)
    record('All eight primary navigation tabs render',page.locator('.tabs .tab').count()==8)
    record('No horizontal overflow at 1120px',page.evaluate('document.documentElement.scrollWidth<=window.innerWidth'))
    page.screenshot(path=str(SHOTS/'overview.png'),full_page=True)
    for name in ['cpu','memory','disk','network','gpu','battery','projects']:
        page.locator(f'.tabs [data-nav="{name}"]').click()
        record(f'{name} tab renders',page.locator('#content').inner_text().strip()!='')
        record(f'{name} has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=window.innerWidth'))
    page.locator('.tabs [data-nav="memory"]').click()
    page.locator('#app-search').fill('chrome')
    record('Case-insensitive app search filters results',page.locator('.app-row').count()==1)
    record('Search keeps focus through rerenders',page.locator('#app-search').evaluate('(x)=>x===document.activeElement'))
    page.locator('.app-row').click()
    record('Expand shows all 94 Chrome processes',page.locator('.process-detail .process-row').count()==95)
    record('Graceful quit action is shown',page.locator('[data-quit-app]').count()==1)
    page.locator('[data-quit-app]').click()
    record('Demo does not terminate any process','no apps' in page.locator('#toast').inner_text())
    page.locator('#app-search').fill('')
    page.locator('#background-toggle').check()
    record('Background group can be included',page.locator('.app-row').count()==10)
    page.locator('#background-toggle').uncheck()
    record('Background group can be excluded',page.locator('.app-row').count()==9)
    page.locator('[data-sort="cpu"]').click()
    record('Sort by CPU places Chrome first','Google Chrome' in page.locator('.app-row').first.inner_text())
    page.locator('#app-search').fill('this-app-does-not-exist')
    record('No-match state is explicit',page.get_by_text('Nothing matched your search').is_visible())
    page.locator('#app-search').fill('');page.evaluate("Pulse.navigate('memory')")
    page.wait_for_timeout(5600)
    page.screenshot(path=str(SHOTS/'memory.png'),full_page=True)
    page.locator('.tabs [data-nav="projects"]').click()
    record('Project rows and port controls render',page.locator('.project-row').count()==7 and page.locator('.port').count()==8)
    record('Low-CPU is not labelled idle','Low CPU does not mean unused' in page.locator('#content').inner_text())
    page.locator('[data-stop]').first.click()
    record('Demo stop action is non-destructive','no apps' in page.locator('#toast').inner_text())
    page.wait_for_timeout(5600);page.screenshot(path=str(SHOTS/'projects.png'),full_page=True)
    page.locator('.top-actions [data-nav="settings"]').click()
    page.locator('[data-setting="theme"]').select_option('dark')
    record('Theme changes persist in state',page.evaluate('Pulse.getState().settings.theme')=='dark')
    record('Dark theme is applied',page.locator('html').get_attribute('data-theme')=='dark')
    page.locator('[data-setting="interval"]').select_option('5')
    record('Sampling interval updates',page.evaluate('Pulse.getState().settings.interval')==5)
    page.locator('[data-setting="alerts"]').uncheck()
    record('Alerts can be disabled',page.evaluate('Pulse.getState().settings.alerts') is False)
    page.locator('.top-actions [data-nav="alerts"]').click()
    record('Disabled alerts state is shown',page.get_by_text('Alerts are off.').is_visible())
    record('Alert history renders',page.locator('.alert-card').count()==2)
    page.locator('[data-action="clearAlerts"]').click()
    record('Clear alerts removes history',page.locator('.alert-card').count()==0)
    page.locator('.top-actions [data-action="pause"]').click()
    record('Pause updates state',page.evaluate('Pulse.getState().paused') is True)
    page.locator('.top-actions [data-action="pause"]').click()
    record('Resume updates state',page.evaluate('Pulse.getState().paused') is False)
    page.evaluate("Pulse.navigate('overview')");page.screenshot(path=str(SHOTS/'dark-overview.png'),full_page=True)
    # Null and restricted data should not turn into fake zero-percent readings.
    page.evaluate("""() => {const s=structuredClone(PulseDemoFixture);s.snapshot.gpu.available=false;s.snapshot.gpu.usage=null;s.history.forEach(h=>h.gpu=null);s.snapshot.battery.available=false;s.snapshot.battery.percent=null;Pulse.receive(s);} """)
    page.locator('.tabs [data-nav="gpu"]').click()
    record('Missing GPU metric is not fabricated',page.locator('.hero-number').inner_text()=='—')
    page.locator('.tabs [data-nav="battery"]').click()
    record('No-battery state works',page.get_by_text('No internal battery detected').is_visible())
    # Untrusted names must remain inert text.
    page.evaluate("""() => {const s=structuredClone(PulseDemoFixture);s.snapshot.apps[0].name='<img src=x onerror=alert(1)>';Pulse.receive(s);Pulse.navigate('memory');} """)
    record('Application names are HTML-escaped',page.locator('.app-row .app-name').first.inner_text()=='<img src=x onerror=alert(1)>')
    record('Escaped app names do not create elements',page.locator('.app-row .app-name img').count()==0)
    # Valid numeric zero must stay zero; null/NaN must stay unavailable.
    values=page.evaluate("""() => ({z:PulseTesting.byteText(0),n:PulseTesting.byteText(null),nan:PulseTesting.byteText(NaN),p:PulseTesting.pct(0),r:PulseTesting.rateText(0)})""")
    record('Zero/null/NaN formatting is distinct',values=={'z':'0 B','n':'—','nan':'—','p':'0.0%','r':'0 B/s'})
    page.set_viewport_size({'width':860,'height':650});page.evaluate('Pulse.receive(PulseDemoFixture);Pulse.navigate("overview")')
    record('Minimum 860px width has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=window.innerWidth'))
    # Menu mode: native NSStatusItem/NSPopover itself cannot run on Linux.
    m=browser.new_page(viewport={'width':420,'height':660},device_scale_factor=1)
    m.on('pageerror',lambda e:errors.append(str(e)))
    load_ui(m,menu=True);m.wait_for_function('window.Pulse.getState().snapshot !== null')
    record('Menu popover has six compact cards',m.locator('.menu-card').count()==6)
    record('Menu popover fits 420px width',m.evaluate('document.documentElement.scrollWidth<=window.innerWidth'))
    record('Menu popover fits 660px height',m.evaluate('document.documentElement.scrollHeight<=window.innerHeight'))
    m.screenshot(path=str(SHOTS/'menubar.png'),full_page=True)
    for name in ['cpu','memory','disk','network','gpu','battery','projects']:
        m.locator(f'.tabs [data-nav="{name}"]').click()
        record(f'Menu {name} tab renders',bool(m.locator('.menu-shell').inner_text()))
    blank=browser.new_page(viewport={'width':1120,'height':820});load_ui(blank,demo=False)
    record('No fixture is loaded by default',blank.evaluate('Pulse.getState().snapshot===null'))
    record('Standalone page explains lack of native access','does not have system access' in blank.locator('#content').inner_text())
    record('No uncaught JavaScript errors',not errors)
    browser.close()
report={'passed':len(results),'failed':0,'tests':results,'javascript_errors':errors,'environment':'Linux Chromium, in-memory local assets; deterministic labelled demo fixtures. Production CSP retained in shipped files, omitted only by test harness. No native macOS execution.'}
(ROOT/'tests/ui-test-report.json').write_text(json.dumps(report,indent=2))
print(json.dumps({'passed':len(results),'errors':errors},indent=2))
