'use strict';
(() => {
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const native=Boolean(window.webkit?.messageHandlers?.pulse), menu=window.PULSE_MODE==='menu';
const demo=!native&&new URLSearchParams(location.search).get('demo')==='1';
let state={snapshot:null,history:[],settings:{interval:2,theme:'system',alerts:false,cpuThreshold:80,cpuDuration:60,growthMB:512,hideDock:false,launchAtLogin:false},alerts:[],paused:false,icons:{}};
let page='overview',query='',includeBackground=false,sort='memory',descending=true,expanded=null,toastTimer=null;
const paths={
 pulse:'M2 12h4l3-8 5 16 3-8h5',overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',
 cpu:'M7 7h10v10H7zM9 1v4m6-4v4M9 19v4m6-4v4M1 9h4m-4 6h4m14-6h4m-4 6h4M10 10h4v4h-4z',
 memory:'M3 6h18v11H3zM6 17v4m4-4v4m4-4v4m4-4v4M7 9v4m5-4v4m5-4v4',disk:'M4 4h16l2 11H2L4 4zM2 15v5h20v-5M6 17.5h.01M10 17.5h.01',
 network:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18Z',
 gpu:'m12 2 9 5-9 5-9-5 9-5Zm-9 10 9 5 9-5M3 17l9 5 9-5',battery:'M2 6h17v12H2zM22 10v4M5 9h8v6H5z',projects:'M3 5h7l2 3h9v12H3V5Z',
 settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3ZM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
 bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4',pause:'M8 4v16M16 4v16',play:'m7 4 13 8-13 8V4Z',
 download:'M12 2v13m-5-5 5 5 5-5M4 16v5h16v-5',search:'M16 10a6 6 0 1 1-12 0 6 6 0 0 1 12 0ZM15 15l6 6',
 shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Zm-4 9 3 3 5-6',arrow:'M5 12h14m-6-6 6 6-6 6',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v6l4 2',
 stop:'M5 5h14v14H5z',external:'M14 3h7v7m0-7L10 14M10 3H3v18h18v-7',folder:'M3 5h7l2 3h9v12H3V5Z',info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 11v6m0-10v1',
 check:'m4 12 5 5L20 6',activity:'M3 17 8 9l4 5 5-10 4 4',bolt:'m13 2-9 12h7l-1 8 10-13h-7l1-7Z',close:'m6 6 12 12M6 18 18 6'
};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.activity}"/></svg>`;
const tabs=['overview','cpu','memory','disk','network','gpu','battery','projects'];
const names={overview:'Overview',cpu:'CPU',memory:'Memory',disk:'Disk',network:'Network',gpu:'GPU',battery:'Battery',projects:'Projects',settings:'Settings',alerts:'Alerts'};
const accent=n=>`--accent:var(--${['overview','settings','alerts'].includes(n)?'cpu':n==='projects'?'orange':n})`;
const finite=v=>typeof v==='number'&&Number.isFinite(v);
const scalar=v=>finite(v)?v.toFixed(2):'—';
function bytes(v,binary=true){if(!finite(v))return {n:'—',u:''};const units=binary?['B','KiB','MiB','GiB','TiB']:['B','KB','MB','GB','TB'],base=binary?1024:1000;let k=0;while(v>=base&&k<4){v/=base;k++;}return {n:v.toFixed(k===0?0:v>=100?1:2).replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,''),u:units[k]};}
const byteText=(v,binary=true)=>{const f=bytes(v,binary);return `${f.n}${f.u?' '+f.u:''}`;};
const byteHTML=(v,binary=true)=>{const f=bytes(v,binary);return `${f.n}<span class="unit">${f.u}</span>`;};
const pct=v=>finite(v)?`${v.toFixed(v<10?1:0)}%`:'—';
const pctHTML=v=>finite(v)?`${v.toFixed(0)}<span class="unit">%</span>`:'—';
const rateText=v=>finite(v)?byteText(v,false)+'/s':'—';
const rateHTML=v=>{const f=bytes(v,false);return `${f.n}<span class="unit">${f.u?f.u+'/s':''}</span>`;};
const duration=s=>{if(!finite(s))return '—';s=Math.max(0,Math.floor(s));const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return d?`${d}d ${h}h`:h?`${h}h ${m}m`:m?`${m}m`:`${s}s`;};
const time=t=>new Date(t*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
function send(action,payload={}){
 if(native){window.webkit.messageHandlers.pulse.postMessage({action,...payload});return;}
 if(action==='ready')return;
 if(!demo){toast('Live monitoring requires the macOS app. This browser page cannot inspect your Mac.');return;}
 if(action==='pause'){state.paused=!state.paused;render();}
 else if(action==='saveSettings'){Object.assign(state.settings,payload.settings);render();}
 else if(action==='clearAlerts'){state.alerts=[];render();}
 else if(action==='settings')navigate('settings');
 else if(action==='open')navigate('overview');
 else toast('Demo preview — no apps, ports, files, or system settings were changed.');
}
function toast(message){const t=$('#toast');t.textContent=Array.isArray(message)?message[0]:String(message);t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),5500);}
function navigate(n){if(!names[n])return;page=n;expanded=null;query='';sort=n==='cpu'?'cpu':'memory';descending=true;render();window.scrollTo(0,0);}
function history(key,count=60){return state.history.slice(-count).map(p=>p[key]);}
function chart(values,{large=false,scale=null,label='Recent samples',bars=false}={}){
 const valid=values.filter(finite);
 if(!valid.length)return '<div class="missing-chart">Waiting for a measured sample</div>';
 const w=600,h=large?140:34,max=scale||Math.max(...valid,1)*1.12,min=0;
 const y=v=>(h-3)-(Math.max(min,Math.min(max,v))/max)*(h-8),x=i=>values.length===1?w/2:i*w/(values.length-1);
 let shape='';
 if(bars){const bw=w/Math.max(values.length,30);shape=values.map((v,i)=>finite(v)?`<rect x="${i*bw+1}" y="${y(v)}" width="${Math.max(1,bw-2)}" height="${Math.max(1,h-y(v))}" rx="1" fill="currentColor" opacity=".85"/>`:'').join('');}
 else{
  let segments=[],current=[];values.forEach((v,i)=>{if(finite(v))current.push([x(i),y(v)]);else if(current.length){segments.push(current);current=[];}});if(current.length)segments.push(current);
  shape=segments.map(ps=>{const pts=ps.map(p=>p.map(n=>n.toFixed(2)).join(',')).join(' ');return `<polygon points="${ps[0][0]},${h} ${pts} ${ps[ps.length-1][0]},${h}" fill="currentColor" opacity=".12"/><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="${large?2:1.7}" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round"/>${ps.length===1?`<circle cx="${ps[0][0]}" cy="${ps[0][1]}" r="2" fill="currentColor"/>`:''}`;}).join('');
 }
 return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="${esc(label)}">${large?[.25,.5,.75].map(f=>`<line x1="0" x2="600" y1="${h*f}" y2="${h*f}" stroke="currentColor" opacity=".08"/>`).join(''):''}${shape}</svg>`;
}
function ring(items,center,caption){const sum=items.reduce((n,x)=>n+Math.max(0,x.value||0),0)||1,circ=2*Math.PI*42;let offset=0;return `<div class="ring"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="42" fill="none" stroke="var(--line)" stroke-width="8"/>${items.map(i=>{const len=Math.max(0,i.value||0)/sum*circ;const a=`<circle cx="50" cy="50" r="42" fill="none" stroke="${i.color}" stroke-width="8" stroke-dasharray="${Math.max(0,len-1.8)} ${circ}" stroke-dashoffset="${-offset}"/>`;offset+=len;return a;}).join('')}</svg><div class="ring-label">${esc(center)}<small>${esc(caption)}</small></div></div>`;}
function appIcon(a,small=false){const uri=state.icons?.[a.id];return `<span class="app-icon${small?' small':''}">${typeof uri==='string'&&/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(uri)?`<img src="${uri}" alt="">`:esc(a.name?.slice(0,2).toUpperCase()||'AP')}</span>`;}
const allApps=()=>state.snapshot?.apps||[];
function appsSorted(key='memory',include=false){return allApps().filter(a=>include||a.id!=='__background__').slice().sort((a,b)=>(b[key]||0)-(a[key]||0));}
function titleBlock(title,subtitle,right=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="heading-meta">${right}</div></div>`;}
function tabBar(){return `<nav class="tabs" aria-label="Monitoring categories">${tabs.map(n=>`<button class="tab${page===n?' active':''}" style="${accent(n)}" data-nav="${n}" aria-label="${names[n]}" aria-current="${page===n?'page':'false'}">${icon(n)}${menu?'':names[n]}</button>`).join('')}</nav>`;}
function miniStat(label,value){return `<div class="mini-stat"><label>${label}</label><span>${value}</span></div>`;}
function metricCard(n,subtitle,value,stats,badge=''){
 const s=state.snapshot,h=history(n),available=n==='disk'?s.disk.available:s[n]?.available;
 return `<button class="metric-card" data-nav="${n}" style="${accent(n)}"><div class="card-title"><span class="left"><span class="tint-icon">${icon(n)}</span>${names[n]}</span><span class="chevron" aria-hidden="true">›</span></div><div class="card-subtitle">${subtitle}</div><div class="metric-main"><div class="metric-value">${value}</div>${badge}</div><div class="mini-stats">${stats.map(x=>miniStat(...x)).join('')}</div><div class="${available?'microchart':'missing-chart'}">${available?chart(h,{bars:true,scale:['cpu','gpu','battery'].includes(n)?100:n==='memory'?s.memory.total:null,label:`${names[n]} recent samples`}):n==='gpu'?'System-wide utilization unavailable':n==='battery'?'No internal battery':n==='network'?'Waiting for interface deltas':'Waiting for a measured sample'}</div></button>`;
}
function busyList(count=3){return appsSorted('cpu').slice(0,count).map(a=>`<div class="busy-row">${appIcon(a,true)}<span class="busy-name">${esc(a.name)}</span><strong>${pct(a.cpu)}</strong></div>`).join('')||'<div class="summary-note">No readable app processes yet.</div>';}
function overview(){
 const s=state.snapshot,m=s.memory,b=s.battery,g=s.gpu,n=s.network,d=s.disk;
 const memItems=[{label:'App',value:m.available?m.app:null,color:'var(--memory)'},{label:'Wired',value:m.available?m.wired:null,color:'var(--disk)'},{label:'Compressed',value:m.available?m.compressed:null,color:'var(--network)'},{label:'Available',value:m.available?m.free:null,color:'var(--line)'}];
 const tops=appsSorted('memory').slice(0,3),sumApps=appsSorted('memory').reduce((n,a)=>n+a.memory,0);
 const appItems=tops.map((a,i)=>({label:a.name,value:a.memory,color:['var(--memory)','var(--cpu)','var(--network)'][i]}));appItems.push({label:'Other apps',value:Math.max(0,sumApps-tops.reduce((t,a)=>t+a.memory,0)),color:'var(--line)'});
 const leg=items=>`<div class="legend">${items.map(i=>`<div class="legend-row"><span class="name"><span class="dot" style="--swatch:${i.color}"></span>${esc(i.label)}</span><strong>${byteText(i.value)}</strong></div>`).join('')}</div>`;
 return titleBlock('Your Mac, at a glance.','A clear picture of what’s running. Every helper counted.',`<strong>${esc(s.chip||s.model)}</strong><br>${s.appCount} app groups · ${s.processCount.toLocaleString()} processes`)+
 `<div class="grid metrics-grid">${metricCard('cpu','Across all '+s.cpu.cores+' logical cores',pctHTML(s.cpu.usage),[['User',pct(s.cpu.user)],['System',pct(s.cpu.system)],['Load average',scalar(s.cpu.load1)]])}
 ${metricCard('memory','In use of '+byteText(m.total),m.available?byteHTML(m.used):'—',[['App',byteText(m.app)],['Wired',byteText(m.wired)],['Compressed',byteText(m.compressed)]],`<span class="pill ${m.pressure==='Normal'?'':m.pressure==='Not reported'?'neutral':'warning'}">${esc(m.pressure)}</span>`)}
 ${metricCard('gpu',esc(g.name),pctHTML(g.usage),[['Memory',g.unified?'Unified':'Dedicated'],['Utilization','Unavailable'],['Device',g.deviceAvailable?'Available':'Unavailable']])}
 ${metricCard('disk','Free on your home volume',d.available?byteHTML(d.free,false):'—',[['Reading',rateText(d.read)],['Writing',rateText(d.write)],['Capacity',byteText(d.total,false)]])}
 ${metricCard('network','Downloading · '+esc(n.interfaces.join(', ')||'physical interfaces'),rateHTML(n.download),[['Uploading',rateText(n.upload)],['Received',byteText(n.received,false)],['Sent',byteText(n.sent,false)]])}
 ${metricCard('battery',b.available?(b.charging?'Charging':b.pluggedIn?'Connected to power':'On battery'):'Desktop / no battery',pctHTML(b.percent),[['Remaining',b.charging?'Charging':duration(b.minutes===null?null:b.minutes*60)],['Cycles',b.cycles??'—'],['Health',pct(b.health)]])}</div>
 <div class="grid summary-grid"><section class="summary-card" style="${accent('memory')}"><div class="summary-title">${icon('memory')}Memory by type</div><div class="summary-body">${ring(memItems,m.available?`${Math.round(m.used/m.total*100)}%`:'—','in use')}${leg(memItems)}</div></section>
 <section class="summary-card" style="${accent('memory')}"><div class="summary-title">${icon('overview')}Memory by app</div><div class="summary-body">${ring(appItems,bytes(sumApps).n,bytes(sumApps).u+' in apps')}${leg(appItems)}</div></section>
 <section class="summary-card" style="${accent('cpu')}"><div class="summary-title">${icon('activity')}Busiest right now</div>${busyList()}<div class="summary-note">App CPU: one core = 100%. Includes helper processes.</div></section></div>`;
}
function stat(label,value,progress,ic=''){return `<div class="stat-card"><label>${ic?icon(ic):''}${label}</label><div class="stat-number">${value}</div>${finite(progress)?`<div class="progress"><span style="width:${Math.max(0,Math.min(100,progress))}%"></span></div>`:''}</div>`;}
function hero(metric,label,value,rows,max=null){return `<div class="hero" style="${accent(metric)}"><div class="hero-metric"><div class="eyebrow">${label}</div><div class="hero-number">${value}</div>${rows.map(r=>`<div class="hero-info"><span>${r[0]}</span><span>${r[1]}</span></div>`).join('')}</div><div class="hero-chart"><div class="large-chart">${chart(history(metric,300),{large:true,scale:max,label:`${names[metric]} history`})}</div><div class="chart-caption"><span>${state.history.length>1?'Since '+time(state.history[Math.max(0,state.history.length-300)].t):'Building your live history'}</span><span>${state.paused?'Paused':'Now'}</span></div></div></div>`;}
function appTable(){
 let apps=allApps().filter(a=>(includeBackground||a.id!=='__background__')&&(!query||(a.name+' '+a.processes.map(p=>p.name+' '+p.pid).join(' ')).toLowerCase().includes(query.toLowerCase())));
 apps.sort((a,b)=>((b[sort]||0)-(a[sort]||0))*(descending?1:-1));
 const max=Math.max(...apps.map(a=>a.memory),1);
 return `<section class="table-section" style="${accent(page)}"><div class="table-toolbar"><div class="toolbar-left"><h2>Apps, not a maze of processes.</h2></div><div class="toolbar-left"><label class="small-check"><input id="background-toggle" type="checkbox" ${includeBackground?'checked':''}> Background</label><label class="search">${icon('search')}<input id="app-search" type="search" placeholder="Find an app or PID" value="${esc(query)}" aria-label="Search apps or process IDs"></label></div></div>
 <div class="table-labels"><span>Application <span style="opacity:.65">· ${apps.length}</span></span><button data-sort="cpu" aria-label="Sort by CPU" aria-pressed="${sort==='cpu'}">CPU ${sort==='cpu'?(descending?'↓':'↑'):''}</button><button data-sort="memory" aria-label="Sort by memory" aria-pressed="${sort==='memory'}">Memory ${sort==='memory'?(descending?'↓':'↑'):''}</button><span></span></div>
 ${apps.map(a=>`<button class="app-row${expanded===a.id?' selected':''}" data-expand="${esc(a.id)}" aria-expanded="${expanded===a.id}"><div class="app-cell">${appIcon(a)}<span class="app-label"><span class="app-name">${esc(a.name)}</span><small>${a.count} process${a.count===1?'':'es'}${a.count>1?' · helpers included':''}</small></span></div><div class="numeric cpu">${pct(a.cpu)}</div><div class="numeric">${byteText(a.memory)}<div class="progress"><span style="width:${100*a.memory/max}%"></span></div></div><span class="row-expand">${expanded===a.id?'⌄':'›'}</span></button>${expanded===a.id?processDetail(a):''}`).join('')||empty('search','Nothing matched your search','Try an application name or process ID. Background processes are hidden unless you enable them.')}
 </section><p class="footnote">Memory uses physical footprint where readable, with RSS fallback for restricted processes. Shared pages can be counted more than once; app totals need not match system memory. CPU is macOS’s smoothed per-process reading, with one core = 100%.</p>`;
}
function processDetail(a){return `<div class="process-detail"><div class="detail-top"><p>${esc(a.path||'Services without a detectable app parent')}<br>${a.fallbackCount?`${a.fallbackCount} process(es) use RSS fallback.`:'All readable memory values use physical footprint.'}</p>${a.quitAllowed?`<button class="button danger" data-quit-app="${esc(a.id)}" aria-label="Review and quit ${esc(a.name)}">Quit app…</button>`:''}</div><div class="process-row"><span>PID</span><span>Process</span><span>CPU</span><span>Memory</span></div>${a.processes.map(p=>`<div class="process-row"><span>${p.pid}</span><span class="path" title="${esc(p.path)}">${esc(p.name)}${p.footprint?'':' · RSS'}</span><span>${pct(p.cpu)}</span><span>${byteText(p.memory)}</span></div>`).join('')}</div>`;}
function cpuPage(){const c=state.snapshot.cpu;return titleBlock('CPU','See what’s keeping your Mac busy.',`${c.cores} logical cores · ${esc(state.snapshot.chip)}`)+hero('cpu','TOTAL CPU UTILIZATION',pctHTML(c.usage),[['User',pct(c.user)],['System',pct(c.system)],['Idle',pct(c.idle)]],100)+`<div class="grid stat-grid" style="${accent('cpu')}">${stat('User',pctHTML(c.user),c.user,'cpu')}${stat('System',pctHTML(c.system),c.system,'settings')}${stat('1-minute load',scalar(c.load1),null,'activity')}${stat('Logical cores',c.cores,null,'overview')}${stat('Thermal state',esc(state.snapshot.thermal||'Unavailable'),null,'activity')}</div>`+appTable();}
function memoryPage(){const m=state.snapshot.memory,top=appsSorted()[0];return titleBlock('Memory','Find the apps behind your memory usage.',`${byteText(m.total)} installed · ${esc(m.pressure)} pressure`)+hero('memory','MEMORY IN USE · ESTIMATE',m.available?byteHTML(m.used):'—',[['Available',byteText(m.free)],['Swap used',byteText(m.swap)],['Pressure',esc(m.pressure)]],m.total)+`<div class="grid stat-grid" style="${accent('memory')}">${stat('App memory',byteHTML(m.app),m.app/m.total*100,'overview')}${stat('Wired',byteHTML(m.wired),m.wired/m.total*100,'shield')}${stat('Compressed',byteHTML(m.compressed),m.compressed/m.total*100,'memory')}${stat('Top app',top?byteHTML(top.memory):'—',null,'activity')}</div>`+appTable();}
function infoCard(title,rows){return `<section class="info-card"><h2>${title}</h2>${rows.map(r=>`<div class="info-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('')}</section>`;}
function diskPage(){const d=state.snapshot.disk,available=d.available&&finite(d.total)&&d.total>0&&finite(d.free);const percent=available?`${(d.free/d.total*100).toFixed(1)}%`:'—';return titleBlock('Disk','Storage space and device-level I/O.',esc(d.volume||'Home volume'))+hero('disk','FREE SPACE · HOME VOLUME',available?byteHTML(d.free,false):'—',[['Total capacity',byteText(d.total,false)],['Used',byteText(d.used,false)],['Available',percent]])+`<div class="grid stat-grid" style="${accent('disk')}">${stat('Used space',byteHTML(d.used,false),available?d.used/d.total*100:null,'disk')}${stat('Available',byteHTML(d.free,false),available?d.free/d.total*100:null,'overview')}${stat('Read speed',rateHTML(d.read),null,'download')}${stat('Write speed',rateHTML(d.write),null,'activity')}</div><div class="grid two-col">${infoCard('Home volume',[['Capacity',byteText(d.total,false)],['Free space',byteText(d.free,false)],['Used space',byteText(d.used,false)]])}${infoCard('Reading these numbers',[['Space units','Decimal GB / TB'],['I/O chart','Device read rate'],['Scope','Reported storage drivers']])}</div>${available?'':`<div class="wide-note"><h3>Storage data is unavailable.</h3>macOS did not return valid capacity values for the home volume.</div>`}<div class="wide-note"><h3>Storage space is not a cleanup recommendation.</h3>APFS volumes share container space, and snapshots or purgeable data can make Finder report a different available figure. Device-level I/O may include more than your home volume. Pulse does not delete files or “clean” caches.</div>`;}
function networkPage(){const n=state.snapshot.network;return titleBlock('Network','Live traffic across your physical network interfaces.',esc(n.interfaces.join(' · ')||'Waiting for interfaces'))+hero('network','DOWNLOADING',rateHTML(n.download),[['Uploading',rateText(n.upload)],['Received this session',byteText(n.received,false)],['Sent this session',byteText(n.sent,false)]])+`<div class="grid stat-grid" style="${accent('network')}">${stat('Download',rateHTML(n.download),null,'download')}${stat('Upload',rateHTML(n.upload),null,'activity')}${stat('Received',byteHTML(n.received,false),null,'network')}${stat('Sent',byteHTML(n.sent,false),null,'arrow')}</div><div class="wide-note"><h3>Only interface counters. No packet inspection.</h3>Pulse adds traffic from physical <strong>en*</strong> interfaces and excludes loopback and VPN tunnel counters to avoid double-counting the same transfer. Local network transfers are included, so these are not internet-plan usage totals. Session counters restart when you quit Pulse. Per-app network attribution is not implemented.</div>`;}
function gpuPage(){const g=state.snapshot.gpu;return titleBlock('GPU','Graphics device information. System-wide utilization is unavailable.',esc(g.name))+hero('gpu','SYSTEM-WIDE UTILIZATION',pctHTML(g.usage),[['Device',esc(g.name)],['Architecture',g.unified?'Unified memory':'Discrete / reported'],['Utilization','Unavailable']],100)+`<div class="wide-note"><h3>${g.deviceAvailable?'macOS identifies the graphics device; it does not provide a public system-wide utilization counter here.':'Graphics device information is unavailable.'}</h3>Pulse shows “—” for system-wide GPU utilization. It does not estimate GPU memory, renderer/tiler use, temperature, or power from this app’s own Metal allocation. Unified memory is shared with CPU workloads.</div>`;}
function batteryPage(){const b=state.snapshot.battery;if(!b.available)return titleBlock('Battery','Power information for portable Macs.')+empty('battery','No internal battery detected','Desktop Macs and machines that do not expose an internal battery show this state. It is not an error.');return titleBlock('Battery','Charge, health, and the power state reported by macOS.',b.charging?'Charging':b.pluggedIn?'Connected to power':'Running on battery')+hero('battery','BATTERY LEVEL',pctHTML(b.percent),[['Power source',b.pluggedIn?'Power adapter':'Battery'],[b.charging?'Until full':'Time remaining',duration(b.minutes===null?null:b.minutes*60)],['Condition estimate',pct(b.health)]],100)+`<div class="grid stat-grid" style="${accent('battery')}">${stat('Charge',pctHTML(b.percent),b.percent,'battery')}${stat('Health estimate',pctHTML(b.health),b.health,'shield')}${stat('Cycle count',b.cycles??'—',null,'activity')}${stat('Time estimate',duration(b.minutes===null?null:b.minutes*60),null,'clock')}</div><div class="wide-note"><h3>Estimates, not a battery diagnosis.</h3>Remaining time comes from macOS and can be unavailable while calculating. Health is a best-effort full-charge/design-capacity ratio when the battery driver publishes compatible fields. Pulse does not estimate watts from CPU use, and does not present fabricated “power by app” readings.</div>`;}
function projectsPage(){const ps=state.snapshot.projects,low=ps.filter(p=>p.lowSeconds>=300);return titleBlock('Projects','Local development servers, with the ports and memory they use.',`${ps.length} detected server${ps.length===1?'':'s'} · refreshed about every 10 seconds`)+
 `<div class="notice${low.length?'':' neutral'}">${icon('projects')}<div class="notice-text"><strong>${low.length?`${low.length} server${low.length===1?' has':'s have'} stayed below 1% CPU for five minutes`:'Know what’s still running in the background.'}</strong><p>${low.length?'Low CPU does not mean unused. Review these servers before stopping them.':'Detects your listening Node, Python, Bun, Deno, Ruby, Java, PHP, and Go runtimes.'}</p></div>${low.length?'<button class="button danger" data-action="stopLow">Review & stop…</button>':''}</div>
 <section class="table-section" style="${accent('projects')}">${ps.map(p=>`<div class="project-row"><span class="app-icon">${icon('folder')}</span><div class="project-info"><strong>${esc(p.name)}</strong><small title="${esc(p.cwd||'Working directory unavailable')}">${esc(p.runtime)} · PID ${p.pid} · up ${esc(p.elapsed)} · ${p.cwd?esc(p.cwd):'Working directory unavailable'}</small></div><div class="project-tags">${p.ports.map(port=>`<button class="port" data-port="${port}" title="Open 127.0.0.1:${port} in your browser" aria-label="Open port ${port} in your browser">${port}</button>`).join('')}${p.lowSeconds>=60?`<span class="pill neutral">Low CPU ${duration(p.lowSeconds)}</span>`:`<span class="pill">${pct(p.cpu)} CPU</span>`}</div><div class="project-memory">${byteText(p.memory)}</div>${p.cwd?`<button class="icon-button" data-reveal="${p.pid}" title="Reveal project folder" aria-label="Reveal ${esc(p.name)} folder">${icon('folder')}</button>`:''}<button class="icon-button" data-stop="${p.pid}" title="Review and stop this server" aria-label="Review and stop ${esc(p.name)}">${icon('stop')}</button></div>`).join('')||empty('projects','No supported development servers found','Start a local server, then wait up to 10 seconds. Only listening TCP processes owned by your account and using a recognized runtime are listed.')}</section><p class="footnote">Each row is a listening runtime process, not a complete process-tree project total. Custom compiled binaries, remote servers, UDP-only services, and processes inside containers may not appear. Opening a port assumes HTTP; some servers require HTTPS or another protocol.</p>`;}
function empty(ic,title,body){return `<div class="empty">${icon(ic)}<h3>${title}</h3><p>${body}</p></div>`;}
function settingRow(title,description,control){return `<div class="setting-row"><div><label>${title}</label><p>${description}</p></div>${control}</div>`;}
function toggle(key,label){return `<input class="switch" type="checkbox" data-setting="${key}" aria-label="${label}" ${state.settings[key]?'checked':''}>`;}
function settingsPage(){const s=state.settings;return titleBlock('Make Pulse yours.','Small controls. Clear defaults. Everything stays on this Mac.')+`<div class="settings-wrap"><section class="settings-section"><h2>Appearance & sampling</h2>${settingRow('Appearance','Follow your Mac, or choose a light or dark dashboard.',`<select data-setting="theme" aria-label="Appearance">${['system','light','dark'].map(x=>`<option value="${x}" ${s.theme===x?'selected':''}>${x[0].toUpperCase()+x.slice(1)}</option>`).join('')}</select>`)}${settingRow('Refresh interval','Shorter intervals show more detail but use more resources. Project discovery runs about every 10 seconds.',`<select data-setting="interval" aria-label="Refresh interval">${[1,2,5,10].map(x=>`<option value="${x}" ${s.interval===x?'selected':''}>${x} second${x===1?'':'s'}</option>`).join('')}</select>`)}${settingRow('Menu-bar mode','Hide the Dock icon. Closing the window keeps monitoring in the menu bar.',toggle('hideDock','Menu-bar mode'))}${settingRow('Launch at login','Move Pulse into Applications first. macOS may require approval in Login Items.',toggle('launchAtLogin','Launch at login'))}</section>
 <section class="settings-section"><h2>Resource alerts</h2>${settingRow('Enable alerts','Opt in to sustained CPU and five-minute memory-growth warnings. System banners require notification permission.',toggle('alerts','Enable alerts'))}${settingRow('CPU threshold (%)','App plus helpers; 100% means one fully used logical core. This is not the whole-machine percentage.',`<input type="number" data-setting="cpuThreshold" value="${s.cpuThreshold}" min="10" max="1000" step="10" aria-label="CPU threshold">`)}${settingRow('CPU duration (seconds)','The smoothed CPU reading must stay above the threshold for this long.',`<input type="number" data-setting="cpuDuration" value="${s.cpuDuration}" min="30" max="600" step="30" aria-label="CPU duration">`)}${settingRow('Memory growth (MiB)','Warn after about five minutes when growth exceeds this amount AND 25%. A warning is not proof of a leak.',`<input type="number" data-setting="growthMB" value="${s.growthMB}" min="128" max="8192" step="128" aria-label="Memory growth threshold">`)}</section>
 <section class="settings-section"><h2>Local by design</h2><p class="footnote">No account, API key, telemetry upload, or online service. Pulse reads OS counters and process metadata; it does not read browser pages, documents, passwords, or network packets. Exports can contain process names, local paths, and ports. History and alerts stay in memory and clear when the app quits. Settings are stored in macOS preferences.</p><div style="display:flex;justify-content:space-between;align-items:center;margin-top:18px"><span class="footnote">Pulse Monitor 1.0.0 · macOS 13+<br>Independent recreation; not affiliated with Vitals.</span><button class="button" data-action="export">${icon('download')}Export snapshot…</button></div></section></div>`;}
function alertsPage(){return titleBlock('A quiet heads-up.','Warnings help you investigate. Pulse never quits anything automatically.',`<button class="button" data-action="clearAlerts" ${state.alerts.length?'':'disabled'}>Clear history</button>`)+(!state.settings.alerts?`<div class="notice neutral">${icon('bell')}<div class="notice-text"><strong>Alerts are off.</strong><p>Enable them in Settings to watch for sustained CPU use and growing memory.</p></div><button class="button" data-nav="settings">Open settings</button></div>`:'')+(state.alerts.length?state.alerts.map(a=>`<article class="alert-card">${icon('bell')}<div><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><time>${new Date(a.time*1000).toLocaleString()}</time></div></article>`).join(''):empty('check','No resource warnings this session','Warnings appear only after the configured observation window. Normal resource spikes are not treated as confirmed problems.'));}
function footer(){const s=state.snapshot;return `<footer class="footer"><span class="local">${icon('shield')}On-device only · no account or API key</span><span>${demo?'<span class="demo">DEMO · sample data, not live readings</span>':`${s?.model?esc(s.model)+' · ':''}Updated ${s?time(s.timestamp):'—'}`}</span><button class="text-button" data-nav="settings">Pulse 1.0.0</button></footer>`;}
function mainContent(){if(!state.snapshot)return empty('pulse','Waiting for your first sample',native?'The first CPU and network reading needs two snapshots. You can adjust preferences while the sampler connects.':'Open Pulse Monitor.app on a Mac to collect live readings. This standalone browser page does not have system access.');return ({overview,cpu:cpuPage,memory:memoryPage,disk:diskPage,network:networkPage,gpu:gpuPage,battery:batteryPage,projects:projectsPage}[page]||overview)();}
function mainShell(){return `<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">${icon('pulse')}</span>Pulse Monitor<small>A LITTLE MORE CLARITY.</small></div><div class="top-actions"><span class="live-badge${demo?' demo':''}"><span class="live-dot${state.paused?' paused':''}"></span>${demo?'Demo data':state.paused?'Monitoring paused':state.snapshot?'Live · every '+state.settings.interval+'s':'Connecting'}</span><button class="icon-button" data-action="pause" title="${state.paused?'Resume':'Pause'} monitoring" aria-label="${state.paused?'Resume':'Pause'} monitoring">${icon(state.paused?'play':'pause')}</button><button class="icon-button" data-action="export" title="Export snapshot" aria-label="Export snapshot">${icon('download')}</button><button class="icon-button" data-nav="alerts" title="Resource alerts" aria-label="Resource alerts">${icon('bell')}</button><button class="icon-button" data-nav="settings" title="Settings" aria-label="Settings">${icon('settings')}</button></div></header>${tabBar()}<main id="content">${page==='settings'?settingsPage():page==='alerts'?alertsPage():mainContent()}</main>${footer()}</div>`;}
function menuOverview(){const s=state.snapshot;if(!s)return empty('pulse','Connecting…','Waiting for the native sampler.');const cards=[['cpu',pctHTML(s.cpu.usage),`Load ${scalar(s.cpu.load1)}`],['memory',byteHTML(s.memory.used),`of ${byteText(s.memory.total)}`],['network',rateHTML(s.network.download),'↑ '+rateText(s.network.upload)],['disk',byteHTML(s.disk.free,false),'free on home volume'],['gpu',pctHTML(s.gpu.usage),s.gpu.deviceAvailable?s.gpu.name:'Device unavailable'],['battery',pctHTML(s.battery.percent),s.battery.available?(s.battery.pluggedIn?'Connected to power':duration(s.battery.minutes===null?null:s.battery.minutes*60)+' remaining'):'No internal battery']];return `<div class="menu-grid">${cards.map(([n,v,sub])=>`<button class="menu-card" style="${accent(n)}" data-nav="${n}"><div class="card-title">${icon(n)}${names[n]}</div><div class="metric-value">${v}</div><div class="menu-sub">${esc(sub)}</div><div class="microchart">${chart(history(n),{scale:['cpu','gpu','battery'].includes(n)?100:n==='memory'?s.memory.total:null,label:`${names[n]} recent samples`})}</div></button>`).join('')}</div><div class="summary-card"><div class="summary-title">Busiest right now · one core = 100%</div>${busyList()}</div>`;}
function menuDetail(){const s=state.snapshot;if(!s)return '';if(page==='projects')return `<h2 class="menu-detail-title">Local servers</h2><div class="menu-list">${s.projects.map(p=>`<div class="menu-item">${icon('folder')}<span class="name">${esc(p.name)}<small style="display:block;color:var(--muted);margin-top:5px">${p.ports.join(', ')}</small></span><strong>${byteText(p.memory)}</strong></div>`).join('')||empty('folder','No servers found','Run a supported local server to see it here.')}</div><div class="wide-note">Open the full dashboard to inspect folders and review stop actions.</div>`;
 const metric=s[page],val=['cpu','gpu'].includes(page)?pctHTML(metric.usage):page==='memory'?byteHTML(metric.used):page==='disk'?byteHTML(metric.free,false):page==='network'?rateHTML(metric.download):pctHTML(metric.percent);
 return `<div style="${accent(page)}"><h2 class="menu-detail-title">${names[page]}</h2><div class="menu-detail-number">${val}</div><div class="large-chart">${chart(history(page,90),{large:true,scale:['cpu','gpu','battery'].includes(page)?100:page==='memory'?s.memory.total:null,label:`${names[page]} history`})}</div>${['cpu','memory'].includes(page)?`<div class="summary-card" style="margin-top:20px"><div class="summary-title">Top app groups · helpers included</div>${appsSorted(page==='cpu'?'cpu':'memory').slice(0,5).map(a=>`<div class="busy-row">${appIcon(a,true)}<span class="busy-name">${esc(a.name)}</span><strong>${page==='cpu'?pct(a.cpu):byteText(a.memory)}</strong></div>`).join('')}</div>`:`<div class="wide-note">${page==='gpu'?'System-wide GPU utilization is unavailable through this public telemetry path.':page==='network'?'Physical-interface traffic; session totals restart when Pulse quits.':page==='battery'?'Battery estimates are reported by macOS and may be unavailable.':'Free space on the home volume. The chart shows device read rate.'}</div>`}</div>`;}
function menuShell(){return `<div class="menu-shell">${tabBar()}<div class="menu-heading"><span>${demo?'DEMO · ':''}${names[page]?.toUpperCase()||'OVERVIEW'}</span><span>${state.paused?'Paused':'Up '+duration(state.snapshot?.uptime)}</span></div>${page==='overview'?menuOverview():menuDetail()}<div class="menu-footer"><button data-action="open">Open Pulse</button><button data-action="settings">Settings…</button><button data-action="quit">Quit</button></div></div>`;}
function render(){
 const theme=state.settings.theme;if(theme==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.setAttribute('data-theme',theme);
 const active=document.activeElement,id=active?.id,selection=id==='app-search'?active.selectionStart:null,scroll=window.scrollY;
 const setting=active?.dataset?.setting;
 // Do not destroy an in-progress preferences edit on a sampling tick.
 if(setting&&page==='settings')return;
 $('#app').innerHTML=menu?menuShell():mainShell();
 if(id){const el=document.getElementById(id);if(el){el.focus({preventScroll:true});if(selection!==null&&typeof el.setSelectionRange==='function'){try{el.setSelectionRange(selection,selection);}catch{}}}}
 window.scrollTo(0,scroll);
}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.nav){if(menu&&['settings','alerts'].includes(b.dataset.nav))send('settings');else navigate(b.dataset.nav);}
 else if(b.dataset.action)send(b.dataset.action);
 else if(b.dataset.expand){expanded=expanded===b.dataset.expand?null:b.dataset.expand;render();}
 else if(b.dataset.sort){if(sort===b.dataset.sort)descending=!descending;else {sort=b.dataset.sort;descending=true;}render();}
 else if(b.dataset.quitApp)send('quitApp',{id:b.dataset.quitApp});
 else if(b.dataset.stop)send('stopProject',{pid:Number(b.dataset.stop)});
 else if(b.dataset.port)send('openPort',{port:Number(b.dataset.port)});
 else if(b.dataset.reveal)send('revealProject',{pid:Number(b.dataset.reveal)});
});
document.addEventListener('input',e=>{if(e.target.id==='app-search'){query=e.target.value;render();}});
document.addEventListener('change',e=>{
 if(e.target.id==='background-toggle'){includeBackground=e.target.checked;render();return;}
 const key=e.target.dataset.setting;if(!key)return;
 const v=e.target.type==='checkbox'?e.target.checked:['interval','cpuThreshold','cpuDuration','growthMB'].includes(key)?Number(e.target.value):e.target.value;
 if(typeof v==='number'&&!Number.isFinite(v)){toast('Enter a valid number.');return;}
 e.target.blur();send('saveSettings',{settings:{[key]:v}});
});
document.addEventListener('keydown',e=>{
 if((e.metaKey||e.ctrlKey)&&/^[1-8]$/.test(e.key)){e.preventDefault();navigate(tabs[Number(e.key)-1]);}
 if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='f'){e.preventDefault();if(!['cpu','memory'].includes(page))navigate('memory');$('#app-search')?.focus();}
 if(e.key==='Escape'&&expanded){expanded=null;render();}
});
window.Pulse={receive(next){state={...state,...next};render();},navigate,toast,getState:()=>state};
window.PulseTesting={bytes,byteText,pct,rateText,duration,esc,chart,native,demo};
render();send('ready');
if(demo){const script=document.createElement('script');script.src='demo.js';document.head.appendChild(script);}
})();
